// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Boggle.Models
{
    [Table("Words", Schema = "boggle")]
    [Index("ID", Name = "ix_boggle_Words_index")]
    public partial class Words
    {
        [Key]
        public int ID { get; set; }
        [Column("Word")]
        [Unicode(false)]
        public string Word { get; set; }
    }
}